### PR TITLE
add extra legislation constant

### PR DESCRIPTION
**Pull request by StupidCodeFactory**
Add a new legislation

### CODE REVIEW

**Comment by StupidCodeFactory** [comment]
[Add legislation to constants](https://trello.com/c/mxZeqgfb/983-add-legislation-to-constants)

**Review by nasirkhanbeis — APPROVED** [review]
Just had a quick look and seems good to me. 
Tested corrective action and test results in TS flow and edit same.

**Review by tobyhughes — COMMENTED** [review]
Checked:
- adding case as TS
- adding supporting info 
- editing
- type ahead

all working as expected for test results and corrective actions

**Review by tobyhughes — APPROVED** [review]
See previous comment!

**Review by slorek — APPROVED** [review]

**Pull request merged**
