### PR TITLE
Convert all remaining Slim templates to ERB

### PR DESCRIPTION
**Pull request by slorek**
https://trello.com/c/dyAlPM07/1128-convert-remaining-slim-templates-to-erb

Per https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/doc/decisions/0001-use-erb-for-view-templates.md

This completes the conversion of all remaining Slim format templates to ERB format.

It also removes the Slim dependencies and linting tasks and updates the documentation. I have moved the Slim gem dependency to the `govuk-design-system-rails` gem, where there are still several templates to convert.

I have tested most but not all of the pages locally. This will need some basic regression testing of the affected pages and detailed design testing as there may be small whitespace issues which may or may not be a problem.

### CODE REVIEW

**Review by KyleMacPherson — COMMENTED** [review]
Looks like there is a slight styling issue on this one:

Screen Shot 2021-08-31 at 10 26 14
Screen Shot 2021-08-31 at 10 26 41

**Review by KyleMacPherson — COMMENTED** [review]
[Minor] Seems like the padding looks a little different here (and maybe some other places?)

Screen Shot 2021-08-31 at 10 36 24
Screen Shot 2021-08-31 at 10 36 34

**Comment by DH02** [comment]
Visually I couldn't find any white-space or layout issues/changes  [differences between the pr and staging] when comparing pages against each other via large sections of the services.

**Review by DH02 — APPROVED** [review]
Visually I couldn't find any white-space or layout issues/changes [differences between the pr and staging] when comparing pages against each other via large sections of the services.

**Comment by DH02** [comment]
The spacing seen in the header (beta tag) etc - on my two accounts the presence and absence of the 'Home' link in the main nav seems to technically impact this - but I think the beta tag is being removed soon?

**Comment by DH02** [comment]
> [Minor] Seems like the padding looks a little different here (and maybe some other places?)
> 
> Screen Shot 2021-08-31 at 10 36 24
> 
> Screen Shot 2021-08-31 at 10 36 34

The spacing seen in the header (the beta tag) etc - on my two accounts, seems to be technically impacted by presence and absence of the 'Home' link in the main nav - but I think the beta tag is being removed soon?

**Comment by KyleMacPherson** [comment]
> > [Minor] Seems like the padding looks a little different here (and maybe some other places?)
> > Screen Shot 2021-08-31 at 10 36 24
> > Screen Shot 2021-08-31 at 10 36 34
> 
> The spacing seen in the header (the beta tag) etc - on my two accounts, seems to be technically impacted by presence and absence of the 'Home' link in the main nav - but I think the beta tag is being removed soon?

The beta tag is not being removed anytime soon I don't think. Also the two screenshots are from 2 seperate review apps, neither of which have the home link fyi.

**Review by nasirkhanbeis — APPROVED** [review]
Tested all possible affected pages/journeys. looking good!

**Pull request merged**
